### ISSUE TITLE
failed upload file wav

### ISSUE THREAD

**Issue by tegarkurniawan** [VoicePIN/VoicePIN-REST-Client-example#9]
I tried to do Enrolling wav file but always Provided Audio Input Is Incorrect code 415 although file already wav

**Comment by sycyhy** [comment]
We need more information to help you. Specifically:
- your api-key
- time when it happened
- is it one time bug or it happens everytime?
- recording (if it is possible) 

As this information is private and client-related please send it to the support@voicepin.com

**Comment by tegarkurniawan** [comment]
i am already send email

**Comment by sycyhy** [comment]
For the futher reference - client sent to us recording with invalid RIFF header - closing.

**Comment by tegarkurniawan** [comment]
I use sox already.
I use this command to convert my .wav file : sox source.wav -r 8000 -b 16
-c 1 output.wav
but when I sent the output.wav to the voicepin server the output was
 {"trained":false,"enrollStatus":"SAMPLE_REJECTED"}

Do you have any recipe to covert to requirement wav with sox?
Or would you suggest me the options to convert it with sox?
_sox source.wav -r 8000 -b 16 -c 1 output.wav_

2016-08-18 15:23 GMT+07:00 Łukasz Warzecha notifications@github.com:

**Comment by sycyhy** [comment]
Your wav file is correct.

The output:  {"trained":false,"enrollStatus":"SAMPLE_REJECTED"} means that your audio sample was rejected. That might happen from various of reasons e.g.:
- bad quality of audio
- empty audio
- passphrase mismatch.

In your case I'm pretty sure it is the 3rd case. Your password group on which you are trying to enroll is connected to the "Verify me with my VoicePIN" phrase so in recording you must say exactly this phrase - it wont work on any others.

**Comment by tegarkurniawan** [comment]
Hai,

Saya baru saja menandatangani petisi "@jokowi, Kami Tolak Revisi UU KPK!
#ReformasiDikorupsi" dan ingin tahu apakah Anda dapat membantu dengan
menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 300.000 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/xLG9Wdt68S

Terima kasih!
Tegar
